### ISSUE TITLE
55 test errors on fresh clone

### ISSUE THREAD

**Issue by dmyersturnbull** [bruneli/scalaopt#2]
Steps to reproduce:
1. git clone
2. remove spark subproject from `build.sbt` (because it doesn't compile)
3. `sbt test`

Example error:

```
scalaopt/std-apps/src/test/scala/com.github.bruneli.scalaopt.stdapps.learning.nnet/FFNeuralNetworkTrainerSpec.scala:135: Reference to method intWrapper in class LowPriorityImplicits should not have survived past type checking,
[error] it should have been processed and eliminated during expansion of an enclosing macro.
[error]       val x = for (j <- 1 to 2) yield random.nextGaussian()
[error]                         ^
```

**Comment by bruneli** [comment]
Hello, thanks for commenting, just did following steps:
1. git clone https://github.com/bruneli/scalaopt.git
2. cd scalaopt/
3. sbt test

and I have not found any test failing. In case you are still interested, let me know if you have remaining issues.

**Comment by dmyersturnbull** [comment]
I just tried this again, and it worked.
